version: "3.9"
services: 
    exsclaim:
        build:
            context: .
            target: base
        tty: true
        stdin_open: true
        volumes: 
            - ./exsclaim:/app/exsclaim
            - ./query:/app/query
            - ./run.py:/app/run.py
